"""
Comprehensive mapping of materials to their commodity symbols for market price tracking.
This mapping is used by the market agent to fetch real-time prices from Alpha Vantage.
"""

MATERIAL_TO_SYMBOL = {
    # Precious Metals
    "Gold": "XAUUSD",
    "Silver": "XAGUSD",
    "Platinum": "XPTUSD",
    "Palladium": "XPDUSD",
    
    # Base Metals
    "Copper": "HG",
    "Aluminum": "ALI",
    "Nickel": "NICKEL",
    "Zinc": "ZINC",
    "Lead": "LEAD",
    "Tin": "TIN",
    
    # Energy Materials
    "Coal": "COAL",
    "Natural Gas": "NG",
    "Crude Oil": "CL",
    "Petroleum": "PETROLEUM",
    "Diesel": "DIESEL",
    "Gasoline": "GASOLINE",
    
    # Agricultural Materials
    "Cotton": "CT",
    "Wool": "WOOL",
    "Rubber": "RUBBER",
    "Wood": "WOOD",
    
    # Electronic Materials
    "Silicon": "SILICON",
    "Rare Earth": "REE",
    
    # Chemical Materials
    "Plastic": "PLASTIC",
    "PVC": "PVC",
    "Polyethylene": "PE",
    "Polypropylene": "PP",
    
    # Battery Materials
    "Lithium": "LITHIUM",
    "Cobalt": "COBALT",
    "Graphite": "GRAPHITE",
    "Manganese": "MANGANESE",
    "Nickel": "NICKEL",
    "Copper": "COPPER",
    "Aluminum": "ALUMINUM",
    "Iron": "IRON",
    
    # Common Materials
    "Steel": "HRC",
    "Iron": "IRON",
    "Iron Ore": "IRONORE",
    "Glass": "GLASS",
    "Ceramic": "CERAMIC",
    "Cement": "CEMENT",
    "Concrete": "CONCRETE",
    "Sand": "SAND",
    "Gravel": "GRAVEL",
    "Limestone": "LIMESTONE",
    "Gypsum": "GYPSUM",
    "Marble": "MARBLE",
    "Granite": "GRANITE",
    "Quartz": "QUARTZ",
    "Asphalt": "ASPHALT",
    "Bitumen": "BITUMEN",
    "Clay": "CLAY",
    "Brick": "BRICK",
    "Tile": "TILE",
    
    # Display Materials
    "LCD": "LCD",
    "OLED": "OLED",
    "LED": "LED",
    "Plasma": "PLASMA",
    "E-Paper": "EPAPER",
    "Touch Screen": "TOUCHSCREEN",
    "Glass Panel": "GLASSPANEL",
    "Display Module": "DISPLAYMODULE",
    
    # Component Materials
    "Circuit Board": "PCB",
    "Semiconductor": "SEMICONDUCTOR",
    "Microchip": "MICROCHIP",
    "Resistor": "RESISTOR",
    "Capacitor": "CAPACITOR",
    "Inductor": "INDUCTOR",
    "Transistor": "TRANSISTOR",
    "Diode": "DIODE",
    "IC": "IC",
    "Connector": "CONNECTOR",
    "Switch": "SWITCH",
    "Relay": "RELAY",
    "Sensor": "SENSOR",
    "Actuator": "ACTUATOR",
    "Motor": "MOTOR",
    "Battery": "BATTERY",
    "Power Supply": "POWERSUPPLY",
    "Cooling System": "COOLINGSYSTEM",
    "Housing": "HOUSING",
    "Frame": "FRAME",
    "Cover": "COVER",
    "Seal": "SEAL",
    "Gasket": "GASKET",
    "O-Ring": "ORING",
    "Bearing": "BEARING",
    "Spring": "SPRING",
    "Gear": "GEAR",
    "Belt": "BELT",
    "Chain": "CHAIN",
    "Pulley": "PULLEY",
    "Shaft": "SHAFT",
    "Bolt": "BOLT",
    "Nut": "NUT",
    "Washer": "WASHER",
    "Screw": "SCREW",
    "Rivet": "RIVET",
    "Clip": "CLIP",
    "Bracket": "BRACKET",
    "Mount": "MOUNT",
    "Support": "SUPPORT",
    "Base": "BASE",
    "Stand": "STAND",
    "Foot": "FOOT",
    "Leg": "LEG",
    "Arm": "ARM",
    "Handle": "HANDLE",
    "Knob": "KNOB",
    "Button": "BUTTON",
    "Key": "KEY",
    "Label": "LABEL",
    "Tag": "TAG",
    "Sticker": "STICKER",
    "Decal": "DECAL",
    "Print": "PRINT",
    "Coating": "COATING",
    "Paint": "PAINT",
    "Varnish": "VARNISH",
    "Lacquer": "LACQUER",
    "Enamel": "ENAMEL",
    "Powder": "POWDER",
    "Plating": "PLATING",
    "Anodizing": "ANODIZING",
    "Galvanizing": "GALVANIZING",
    "Heat Treatment": "HEATTREATMENT",
    "Annealing": "ANNEALING",
    "Tempering": "TEMPERING",
    "Quenching": "QUENCHING",
    "Hardening": "HARDENING",
    "Case Hardening": "CASEHARDENING",
    "Nitriding": "NITRIDING",
    "Carburizing": "CARBURIZING",
    "Boronizing": "BORONIZING",
    "Chromizing": "CHROMIZING",
    "Siliconizing": "SILICONIZING",
    "Aluminizing": "ALUMINIZING",
    "Titanizing": "TITANIZING",
    "Vanadizing": "VANADIZING",
    "Niobiumizing": "NIOBIUMIZING",
    "Tantalizing": "TANTALIZING",
    "Molybdenizing": "MOLYBDENIZING",
    "Tungstenizing": "TUNGSTENIZING",
    "Rhenizing": "RHENIZING",
    "Platinizing": "PLATINIZING",
    "Palladizing": "PALLADIZING",
    "Iridizing": "IRIDIZING",
    "Osmizing": "OSMIZING",
    "Ruthenizing": "RUTHENIZING",
    "Rhodiumizing": "RHODIUMIZING",
    "Gold Plating": "GOLDPLATING",
    "Silver Plating": "SILVERPLATING",
    "Copper Plating": "COPPERPLATING",
    "Nickel Plating": "NICKELPLATING",
    "Zinc Plating": "ZINCPLATING",
    "Tin Plating": "TINPLATING",
    "Lead Plating": "LEADPLATING",
    "Cadmium Plating": "CADMIUMPLATING",
    "Chromium Plating": "CHROMIUMPLATING",
    "Manganese Plating": "MANGANESEPLATING",
    "Iron Plating": "IRONPLATING",
    "Cobalt Plating": "COBALTPLATING",
    "Titanium Plating": "TITANIUMPLATING",
    "Vanadium Plating": "VANADIUMPLATING",
    "Niobium Plating": "NIOBIUMPLATING",
    "Tantalum Plating": "TANTALUMPLATING",
    "Molybdenum Plating": "MOLYBDENUMPLATING",
    "Tungsten Plating": "TUNGSTENPLATING",
    "Rhenium Plating": "RHENIUMPLATING",
    "Platinum Plating": "PLATINUMPLATING",
    "Palladium Plating": "PALLADIUMPLATING",
    "Iridium Plating": "IRIDIUMPLATING",
    "Osmium Plating": "OSMIUMPLATING",
    "Ruthenium Plating": "RUTHENIUMPLATING",
    "Rhodium Plating": "RHODIUMPLATING",
    "Gold Coating": "GOLDCOATING",
    "Silver Coating": "SILVERCOATING",
    "Copper Coating": "COPPERCOATING",
    "Nickel Coating": "NICKELCOATING",
    "Zinc Coating": "ZINCCOATING",
    "Tin Coating": "TINCOATING",
    "Lead Coating": "LEADCOATING",
    "Cadmium Coating": "CADMIUMCOATING",
    "Chromium Coating": "CHROMIUMCOATING",
    "Manganese Coating": "MANGANESECOATING",
    "Iron Coating": "IRONCOATING",
    "Cobalt Coating": "COBALTCOATING",
    "Titanium Coating": "TITANIUMCOATING",
    "Vanadium Coating": "VANADIUMCOATING",
    "Niobium Coating": "NIOBIUMCOATING",
    "Tantalum Coating": "TANTALUMCOATING",
    "Molybdenum Coating": "MOLYBDENUMCOATING",
    "Tungsten Coating": "TUNGSTENCOATING",
    "Rhenium Coating": "RHENIUMCOATING",
    "Platinum Coating": "PLATINUMCOATING",
    "Palladium Coating": "PALLADIUMCOATING",
    "Iridium Coating": "IRIDIUMCOATING",
    "Osmium Coating": "OSMIUMCOATING",
    "Ruthenium Coating": "RUTHENIUMCOATING",
    "Rhodium Coating": "RHODIUMCOATING"
} 