"""
Comprehensive mapping of materials to their commodity symbols for market price tracking.
This mapping is used by the market agent to fetch real-time prices from Alpha Vantage.
"""

MATERIAL_TO_SYMBOL = {
    # Precious Metals
    "Gold": "XAUUSD",
    "Silver": "XAGUSD",
    "Platinum": "XPTUSD",
    "Palladium": "XPDUSD",
    "Rhodium": "RHODIUM",
    "Iridium": "IRIDIUM",
    "Osmium": "OSMIUM",
    "Ruthenium": "RUTHENIUM",
    
    # Base Metals
    "Copper": "HG",
    "Aluminum": "ALI",
    "Nickel": "NICKEL",
    "Zinc": "ZINC",
    "Lead": "LEAD",
    "Tin": "TIN",
    "Cobalt": "COBALT",
    "Molybdenum": "MOLY",
    "Titanium": "TITANIUM",
    "Vanadium": "VANADIUM",
    "Tungsten": "TUNGSTEN",
    "Chromium": "CHROMIUM",
    "Manganese": "MANGANESE",
    "Magnesium": "MAGNESIUM",
    "Beryllium": "BERYLLIUM",
    "Cadmium": "CADMIUM",
    "Mercury": "MERCURY",
    "Antimony": "ANTIMONY",
    "Bismuth": "BISMUTH",
    "Selenium": "SELENIUM",
    "Tellurium": "TELLURIUM",
    
    # Steel and Iron
    "Steel": "HRC",
    "Iron": "IRON",
    "Iron Ore": "IRONORE",
    "Scrap Steel": "SCRAP",
    "Stainless Steel": "STAINLESS",
    "Carbon Steel": "CARBONSTEEL",
    "Alloy Steel": "ALLOYSTEEL",
    "Tool Steel": "TOOLSTEEL",
    "Spring Steel": "SPRINGSTEEL",
    "Structural Steel": "STRUCTURALSTEEL",
    "Weathering Steel": "WEATHERINGSTEEL",
    "Galvanized Steel": "GALVANIZED",
    "Cold Rolled Steel": "COLDROLLED",
    "Hot Rolled Steel": "HOTROLLED",
    
    # Energy Materials
    "Coal": "COAL",
    "Natural Gas": "NG",
    "Crude Oil": "CL",
    "Petroleum": "PETROLEUM",
    "Diesel": "DIESEL",
    "Gasoline": "GASOLINE",
    "Kerosene": "KEROSENE",
    "Jet Fuel": "JETFUEL",
    "Biodiesel": "BIODIESEL",
    "Ethanol": "ETHANOL",
    "Uranium": "URANIUM",
    "Thorium": "THORIUM",
    
    # Agricultural Materials
    "Cotton": "CT",
    "Wool": "WOOL",
    "Leather": "LEATHER",
    "Rubber": "RUBBER",
    "Wood": "WOOD",
    "Plywood": "PLYWOOD",
    "Pulp": "PULP",
    "Paper": "PAPER",
    "Hemp": "HEMP",
    "Jute": "JUTE",
    "Sisal": "SISAL",
    "Bamboo": "BAMBOO",
    "Cork": "CORK",
    "Straw": "STRAW",
    
    # Construction Materials
    "Cement": "CEMENT",
    "Concrete": "CONCRETE",
    "Sand": "SAND",
    "Gravel": "GRAVEL",
    "Limestone": "LIMESTONE",
    "Gypsum": "GYPSUM",
    "Marble": "MARBLE",
    "Granite": "GRANITE",
    "Slate": "SLATE",
    "Quartz": "QUARTZ",
    "Asphalt": "ASPHALT",
    "Bitumen": "BITUMEN",
    "Clay": "CLAY",
    "Brick": "BRICK",
    "Tile": "TILE",
    "Aggregate": "AGGREGATE",
    
    # Electronic Materials
    "Silicon": "SILICON",
    "Germanium": "GERMANIUM",
    "Gallium": "GALLIUM",
    "Indium": "INDIUM",
    "Rare Earth": "REE",
    "Neodymium": "NEODYMIUM",
    "Dysprosium": "DYSPROSIUM",
    "Terbium": "TERBIUM",
    "Europium": "EUROPIUM",
    "Yttrium": "YTTRIUM",
    "Lanthanum": "LANTHANUM",
    "Cerium": "CERIUM",
    "Praseodymium": "PRASEODYMIUM",
    "Samarium": "SAMARIUM",
    "Gadolinium": "GADOLINIUM",
    
    # Chemical Materials
    "Plastic": "PLASTIC",
    "PVC": "PVC",
    "Polyethylene": "PE",
    "Polypropylene": "PP",
    "Polystyrene": "PS",
    "Acrylic": "ACRYLIC",
    "Nylon": "NYLON",
    "Polyester": "POLYESTER",
    "Polyurethane": "PU",
    "PTFE": "PTFE",
    "PEEK": "PEEK",
    "POM": "POM",
    "PC": "PC",
    "ABS": "ABS",
    "PET": "PET",
    "PBT": "PBT",
    "PPS": "PPS",
    "PMMA": "PMMA",
    
    # Glass and Ceramics
    "Glass": "GLASS",
    "Ceramic": "CERAMIC",
    "Porcelain": "PORCELAIN",
    "Fiberglass": "FIBERGLASS",
    "Quartz Glass": "QUARTZGLASS",
    "Borosilicate": "BOROSILICATE",
    "Soda Lime": "SODALIME",
    "Lead Glass": "LEADGLASS",
    "Alumina": "ALUMINA",
    "Zirconia": "ZIRCONIA",
    "Silicon Carbide": "SIC",
    "Silicon Nitride": "SIN",
    "Aluminum Nitride": "ALN",
    
    # Textile Materials
    "Polyester Fiber": "POLYFIBER",
    "Nylon Fiber": "NYLONFIBER",
    "Acrylic Fiber": "ACRYLICFIBER",
    "Rayon": "RAYON",
    "Viscose": "VISCOSE",
    "Modal": "MODAL",
    "Lyocell": "LYOCELL",
    "Spandex": "SPANDEX",
    "Aramid": "ARAMID",
    "Carbon Fiber": "CARBONFIBER",
    "Glass Fiber": "GLASSFIBER",
    "Basalt Fiber": "BASALTFIBER",
    
    # Composite Materials
    "Carbon Fiber": "CARBONFIBER",
    "Fiberglass": "FIBERGLASS",
    "Kevlar": "KEVLAR",
    "Graphene": "GRAPHENE",
    "Carbon Nanotube": "CNT",
    "Metal Matrix": "MMC",
    "Ceramic Matrix": "CMC",
    "Polymer Matrix": "PMC",
    "Hybrid Composite": "HYBRID",
    
    # Battery Materials
    "Lithium": "LITHIUM",
    "Cobalt": "COBALT",
    "Graphite": "GRAPHITE",
    "Manganese": "MANGANESE",
    "Nickel": "NICKEL",
    "Copper": "COPPER",
    "Aluminum": "ALUMINUM",
    "Iron": "IRON",
    "Phosphate": "PHOSPHATE",
    "Sulfur": "SULFUR",
    "Electrolyte": "ELECTROLYTE",
    "Separator": "SEPARATOR",
    
    # Semiconductor Materials
    "Silicon Wafer": "SILICONWAFER",
    "Gallium Arsenide": "GAAS",
    "Germanium Wafer": "GERMANIUMWAFER",
    "Silicon Carbide": "SIC",
    "Gallium Nitride": "GAN",
    "Indium Phosphide": "INP",
    "Cadmium Telluride": "CDTE",
    "Copper Indium Gallium Selenide": "CIGS",
    
    # Coating Materials
    "Paint": "PAINT",
    "Varnish": "VARNISH",
    "Lacquer": "LACQUER",
    "Enamel": "ENAMEL",
    "Powder Coating": "POWDERCOAT",
    "Electroplating": "ELECTROPLATE",
    "Anodizing": "ANODIZE",
    "Galvanizing": "GALVANIZE",
    "Chromating": "CHROMATE",
    "Phosphating": "PHOSPHATE",
    
    # Adhesive Materials
    "Glue": "GLUE",
    "Epoxy": "EPOXY",
    "Resin": "RESIN",
    "Sealant": "SEALANT",
    "Adhesive": "ADHESIVE",
    "Mastic": "MASTIC",
    "Caulk": "CAULK",
    "Putty": "PUTTY",
    "Bonding Agent": "BONDING",
    
    # Insulation Materials
    "Fiberglass Insulation": "FIBERGLASSINSUL",
    "Mineral Wool": "MINERALWOOL",
    "Foam": "FOAM",
    "Cellulose": "CELLULOSE",
    "Rock Wool": "ROCKWOOL",
    "Vermiculite": "VERMICULITE",
    "Perlite": "PERLITE",
    "Aerogel": "AEROGEL",
    "Reflective Foil": "REFLECTIVE",
    
    # Packaging Materials
    "Cardboard": "CARDBOARD",
    "Paperboard": "PAPERBOARD",
    "Aluminum Foil": "ALFOIL",
    "Plastic Film": "PLASTICFILM",
    "Bubble Wrap": "BUBBLEWRAP",
    "Foam Packaging": "FOAMPACK",
    "Corrugated": "CORRUGATED",
    "Kraft Paper": "KRAFTPAPER",
    "Shrink Wrap": "SHRINKWRAP",
    
    # Medical Materials
    "Surgical Steel": "SURGICALSTEEL",
    "Medical Grade Plastic": "MEDPLASTIC",
    "Silicone": "SILICONE",
    "Latex": "LATEX",
    "Titanium Implant": "TIIMPLANT",
    "Ceramic Implant": "CERIMPLANT",
    "Bone Cement": "BONECEMENT",
    "Dental Amalgam": "DENTALAMALGAM",
    "Dental Ceramic": "DENTALCERAMIC",
    
    # Aerospace Materials
    "Aerospace Aluminum": "AEROAL",
    "Aerospace Titanium": "AEROTI",
    "Aerospace Steel": "AEROSTEEL",
    "Aerospace Composite": "AEROCOMP",
    "Honeycomb Core": "HONEYCOMB",
    "Aerospace Foam": "AEROFOAM",
    "Aerospace Adhesive": "AEROADHESIVE",
    
    # Automotive Materials
    "Automotive Steel": "AUTOSTEEL",
    "Automotive Aluminum": "AUTOAL",
    "Automotive Plastic": "AUTOPLASTIC",
    "Automotive Rubber": "AUTORUBBER",
    "Automotive Glass": "AUTOGLASS",
    "Automotive Paint": "AUTOPAINT",
    "Automotive Adhesive": "AUTOADHESIVE",
    
    # Marine Materials
    "Marine Steel": "MARINESTEEL",
    "Marine Aluminum": "MARINEAL",
    "Marine Composite": "MARINECOMP",
    "Marine Paint": "MARINEPAINT",
    "Marine Adhesive": "MARINEADHESIVE",
    "Marine Foam": "MARINEFOAM",
    
    # Sports Equipment Materials
    "Sports Composite": "SPORTSCOMP",
    "Sports Foam": "SPORTSFOAM",
    "Sports Rubber": "SPORTSRUBBER",
    "Sports Plastic": "SPORTSPLASTIC",
    "Sports Adhesive": "SPORTSADHESIVE",
    
    # Furniture Materials
    "Furniture Wood": "FURNITUREWOOD",
    "Furniture Metal": "FURNITUREMETAL",
    "Furniture Plastic": "FURNITUREPLASTIC",
    "Furniture Fabric": "FURNITUREFABRIC",
    "Furniture Foam": "FURNITUREFOAM",
    "Furniture Adhesive": "FURNITUREADHESIVE",
    
    # Jewelry Materials
    "Jewelry Gold": "JEWELRYGOLD",
    "Jewelry Silver": "JEWELRYSILVER",
    "Jewelry Platinum": "JEWELRYPLATINUM",
    "Jewelry Diamond": "JEWELRYDIAMOND",
    "Jewelry Gemstone": "JEWELRYGEMSTONE",
    "Jewelry Pearl": "JEWELRYPEARL"
} 